[project]
authors = [{ name = "Muspi Merol", email = "me@muspimerol.site" }]
requires-python = ">=3.12"
dependencies = []

[tool.pdm]
distribution = false

[tool.pdm.scripts]
fmt = { composite = ["ruff format", "ruff check --fix-only"] }

[tool.pdm.dev-dependencies]
dev = ["ruff~=0.5", "python-dotenv~=1.0.1"]
