[project]
authors = [{ name = "Muspi Merol", email = "me@muspimerol.site" }]
requires-python = ">=3.12"
dependencies = [
    "resend~=2.1.0",
    "mistune~=3.0.2",
    "promplate[openai]~=0.3.4.8",
    "promptools[validation]~=0.1.3.5",
    "tenacity~=8.4.2",
    "lunarcalendar~=0.0.9",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
dev = { cmd = ["watchfiles", "python main.py"] }
fmt = { composite = ["ruff format", "ruff check --fix-only"] }

[tool.pdm.dev-dependencies]
dev = ["ruff~=0.5", "python-dotenv~=1.0.1", "watchfiles~=0.22.0"]

[tool.ruff]
line-length = 320
