name: CI

on: [push, fork, pull_request, workflow_dispatch]

jobs:

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: crate-ci/typos@master

  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
      fail-fast: false
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.13
          activate-environment: true
      - name: Install dependencies
        run: |
          uv sync
      - name: Check code quality
        run: |
          ruff format --check --diff
          ruff check --diff
